name: Amit Gupta
description: Experimenting with truth
meta_description: "Experimenting with truth"

aboutPage: true

markdown: redcarpet
highlighter: pygments

paginate: 20
baseurl: /
domain_name: 'http://www.amitgupta.me'
google_analytics: 'UA-47739506-1'
disqus_shortname: 'amitgupta5'

# Details for the RSS feed generator
url:            'http://www.amitgupta.me'
author:         'Amit Gupta'
authorTwitter:  'thedaydreamer9'

permalink:       /:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
